file_dir: "/workspace/Dataset/MUSDB18HQ"
txt_dir: "/workspace/BSRNN/src/files"
txt_path: null
target: ${..train_dataset.target}
is_training: False
is_mono: ${..train_dataset.is_mono}
sr: ${..train_dataset.sr}
